### ISSUE TITLE
Running marbles on marbles.core tests produces errors

### ISSUE THREAD

**Issue by wyegelwel** [twosigma/marbles#72]
* marbles.core version: `python -m marbles --version` 
* marbles.mixins version: `python -m marbles --version`
marbles.core version: 0.9.4
marbles.mixins version: 0.9.4
* Python version: `python --version`
Python 3.5.5
* Operating System: `uname -a`
Linux Ares 4.13.0-43-generic #48-Ubuntu SMP Wed May 16 12:18:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

I cloned marbles from github (https://github.com/twosigma/marbles/), created a fresh conda environment, and installed marbles using python setup.py develop and tried to run python -m marbles on marbles.core tests and got two failures. Using python setup.py test all tests pass.

### What I Did

```
git clone https://github.com/wyegelwel/marbles.git
conda create -n marbles python=3.5
source activate marbles
python setup.py develop
python -m marbles
E..........................................................................E
======================================================================
ERROR: tests.test_log (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_log
Traceback (most recent call last):
  File "/home/wyegelwe/anaconda3/envs/marbles/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/wyegelwe/anaconda3/envs/marbles/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/wyegelwe/sandbox/marbles/marbles/core/tests/test_log.py", line 41, in <module>
    import tests.test_marbles as marbles_tests
  File "/home/wyegelwe/sandbox/marbles/marbles/core/tests/test_marbles.py", line 299, in <module>
    class ExampleTestCase(TestCase, ExampleTestCaseMixin):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases TestCase, ExampleTestCaseMixin


======================================================================
ERROR: tests.test_marbles (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_marbles
Traceback (most recent call last):
  File "/home/wyegelwe/anaconda3/envs/marbles/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/wyegelwe/anaconda3/envs/marbles/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/wyegelwe/sandbox/marbles/marbles/core/tests/test_marbles.py", line 299, in <module>
    class ExampleTestCase(TestCase, ExampleTestCaseMixin):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases TestCase, ExampleTestCaseMixin


----------------------------------------------------------------------
Ran 76 tests in 5.460s

FAILED (errors=2)

```

### Expected behavior
All tests succeed when using python -m marbles

### Additional context
Works with python setup.py test

```
python setup.py test -q
running test
running egg_info
writing dependency_links to marbles.core.egg-info/dependency_links.txt
writing namespace_packages to marbles.core.egg-info/namespace_packages.txt
writing marbles.core.egg-info/PKG-INFO
writing requirements to marbles.core.egg-info/requires.txt
writing top-level names to marbles.core.egg-info/top_level.txt
reading manifest file 'marbles.core.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'marbles.core.egg-info/SOURCES.txt'
running build_ext
.............................ss.....................................ss................................................................................................................................................................
----------------------------------------------------------------------
Ran 230 tests in 6.729s

OK (skipped=4)
```

**Comment by leifwalsh** [comment]
Unfortunately, marbles can not be used to test itself. Somewhat of a watchmen problem. Because our tests do funky things with class resolution, running marbles’s own tests under marbles messes with the method resolution order. 

You should be able to get a decent dev env setup by following the [contributing docs](https://marbles.readthedocs.io/en/stable/contributing.html#get-started), namely, use `tox -e py35` to run the tests against python 3.5 if you’ve set up your env with Pipenv.
